apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: namespace-scope-installation
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: crds-install
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/namespace-scope/litmus-ns-scoped-litmus-portal-manifest.yml
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crds-install
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/namespace-scope/litmus-portal-crds.yml
  prune: true
