---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: manifests-source
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/Jonsy13/manifests-source.git

